[package]
name = "rstk/reactivegraph"
description = "Simple Reactive Graph for Luau"
version = "0.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["benchmarks"]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"