[package]
name = "rstk/compare-with-fusion"
description = ""
version = "0.0.1"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Fusion = "elttob/fusion@0.1.1-beta"
ReactiveGraph = "rstk/reactivegraph@0.1.0"
